""" 
Car Constants
"""

#Obstacle distance
OBSTACLE_ACTION_STOP = 0
OBSTACLE_ACTION_FORWARD = 1
OBSTACLE_ACTION_LEFT = 2
OBSTACLE_ACTION_RIGHT = 3

POLL_DELAY_KERAS = 0.05      # seconds
POLL_DELAY_ULTRASONIC = 0.05 # seconds

