""" 
CAR CONFIG 

This file is read by your car application's manage.py script to change the car
performance. 

EXMAPLE
-----------
import dk
cfg = dk.load_config(config_path='~/d2/config.py')
print(cfg.CAMERA_RESOLUTION)

"""


import os

#PATHS
CAR_PATH = PACKAGE_PATH = os.path.dirname(os.path.realpath(__file__))
DATA_PATH = os.path.join(CAR_PATH, 'data')
MODELS_PATH = os.path.join(CAR_PATH, 'models')

#VEHICLE
DRIVE_LOOP_HZ = 20
MAX_LOOPS = 100000

#CAMERA
CAMERA_RESOLUTION = (160, 120)
CAMERA_FRAMERATE = DRIVE_LOOP_HZ

#STEERING
STEERING_CHANNEL = 0
STEERING_LEFT_PWM = 420
STEERING_RIGHT_PWM = 270

#THROTTLE
THROTTLE_CHANNEL = 1
THROTTLE_FORWARD_PWM = 388
THROTTLE_STOPPED_PWM = 360
THROTTLE_REVERSE_PWM = 327

#TRAINING
BATCH_SIZE = 128
TRAIN_TEST_SPLIT = 0.8


#JOYSTICK
USE_JOYSTICK_AS_DEFAULT = False
JOYSTICK_MAX_THROTTLE = 0.25
JOYSTICK_STEERING_SCALE = 1.0
AUTO_RECORD_ON_THROTTLE = True

#ULTRASONIC SENSORS
ULTRASONIC_FRONT_TRIGGER = 21
ULTRASONIC_FRONT_ECHO = 26

ULTRASONIC_FRONT_LEFT_TRIGGER = 16
ULTRASONIC_FRONT_LEFT_ECHO = 13

ULTRASONIC_FRONT_RIGHT_TRIGGER = 20
ULTRASONIC_FRONT_RIGHT_ECHO = 19

ULTRASONIC_BACK_TRIGGER = 18
ULTRASONIC_BACK_ECHO = 17

ULTRASONIC_BACK_LEFT_TRIGGER = 25
ULTRASONIC_BACK_LEFT_ECHO = 5

ULTRASONIC_BACK_RIGHT_TRIGGER = 23
ULTRASONIC_BACK_RIGHT_ECHO = 27

ULTRASONIC_LEFT_TRIGGER = 12
ULTRASONIC_LEFT_ECHO = 6

ULTRASONIC_RIGHT_TRIGGER = 24
ULTRASONIC_RIGHT_ECHO = 22

